spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/team_management
spring.datasource.username=vineetbanashankari
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
